global:
  resolve_timeout: 5m

route:
  receiver: 'console-receiver'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'console-receiver'
    webhook_configs:
      - url: 'http://localhost:9093/alerts'
